services:

  opus:
    build:
      context: ../
      dockerfile: ./.devcontainer/Containerfile

    image: pergamos/opus:latest
    privileged: true
    network_mode: host

    environment:
      - WSL_DISTRO_NAME=${WSL_DISTRO_NAME}
      - UID=${__OPUS_UUID}
      - GID=${__OPUS_DGID}
      - USER=${USER}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - OPUS_CLI=1

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/${__OPUS_UUID}:/run/user/${__OPUS_UUID}
      - /mnt:/mnt
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - ${HOME}/.tcd/:/home/torizon/.tcd/
      - type: bind
        source: ${PWD}
        target: /workspace
        bind:
          propagation: rshared
      - type: bind
        source: ${PWD}
        target: ${PWD}
        bind:
          propagation: rshared

    container_name: opus-${__OPUS_SHA_DIR}
    stdin_open: true
    tty: true
    pid: host
